name: portfolio
description: "flutter app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

# flutter pub run flutter_native_splash:create
# flutter pub run flutter_native_splash:remove
flutter_native_splash:
  image: assets/images/splash.jpg
  android: true
  ios: true
  fullscreen: true
  color: "#42a5f5"
  color_dark: "#042a49"
  android_gravity: center
  ios_content_mode: scaleAspectFill

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.3.0
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  injectable: ^2.1.2
  go_router: ^9.0.3
  json_annotation: ^4.8.1
  logger: ^1.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.2.3
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^2.0.0
  flutter_native_splash: ^2.1.0
  fluttertoast: ^8.2.6
  image_picker: ^1.1.2
  uuid: ^4.4.2
  timeago: ^3.0.2
  google_generative_ai: ^0.4.4
  country_picker: ^2.0.26

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.4.1
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/splash.jpg