targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/data/dto/display/{{}}.dart': 'lib/generated/{{}}.g.dart'
            '^lib/data/mapper/{{}}.dart': 'lib/generated/{{}}.g.dart'
            '^lib/data/data_source/remote/{{}}.dart': 'lib/generated/{{}}.g.dart'
            '^lib/domain/model/{{}}.dart': 'lib/generated/{{}}.g.dart'
    freezed:
        options:
          build_extensions:
            '^lib/data/dto/display/{{}}.dart': 'lib/generated/{{}}.freezed.dart'
            '^lib/data/mapper/{{}}.dart': 'lib/generated/{{}}.freezed.dart'
            '^lib/domain/model/{{}}.dart': 'lib/generated/{{}}.freezed.dart'
            '^lib/view/pages/home/bloc/menu/{{}}.dart': 'lib/generated/{{}}.freezed.dart'
            '^lib/view/pages/home/bloc/view_module/{{}}.dart': 'lib/generated/{{}}.freezed.dart'