name: my_app
description: my app made by flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  image_picker: ^1.0.1
  firebase_core: ^2.17.0
  firebase_auth: ^4.13.0
  cloud_firestore: ^4.9.3
  firebase_storage: ^11.2.8
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  logger: ^2.0.2+1
  uuid: ^4.1.0
  flutter_svg: ^0.22.0
  flutter_bloc: ^8.0.1
  bloc_concurrency: ^0.2.2
  equatable: ^2.0.3
  carousel_slider: ^4.2.1
  intl: ^0.17.0
  get_it: ^7.6.0
  injectable : ^2.2.0
  go_router: ^9.0.3
  dio: ^5.3.0
  retrofit: ^4.0.3
  google_sign_in: ^6.1.6
  google_fonts: ^6.1.0
  multi_image_picker: ^4.8.1
  flutter_image_compress: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  injectable_generator: ^2.1.6
  retrofit_generator: ^7.0.8

flutter:
  uses-material-design: true
  assets:
    - assets/svg/