### 로그인

POST http://localhost:8080/api/v1/user/login
Content-Type: application/json
Accept-Encoding: UTF-8

{
    "username":"팔로우테스트",
    "password":"팔로우테스트"
}

### 로그인

POST http://localhost:8080/api/v1/user/login
Content-Type: application/json
Accept-Encoding: UTF-8

{
    "username":"test1",
    "password":"test1"
}

### 로그인

POST http://localhost:8080/api/v1/user/login
Content-Type: application/json
Accept-Encoding: UTF-8

{
    "username":"test2",
    "password":"test2"
}

### 로그인

POST http://localhost:8080/api/v1/user/login
Content-Type: application/json
Accept-Encoding: UTF-8

{
    "username":"test3",
    "password":"test3"
}

### 로그인

POST http://localhost:8080/api/v1/user/login
Content-Type: application/json
Accept-Encoding: UTF-8

{
    "username":"test4",
    "password":"test4"
}