"""empty message

Revision ID: 097c3768fd6f
Revises: 
Create Date: 2021-09-22 21:00:00.089908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097c3768fd6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duo',
    sa.Column('host', sa.String(length=20), nullable=False),
    sa.Column('guest', sa.String(length=20), nullable=True),
    sa.Column('search_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('host')
    )
    op.create_table('user',
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('nick_name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('lol_id', sa.String(length=30), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('manner', sa.Integer(), nullable=False),
    sa.Column('register_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nick_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('duo')
    # ### end Alembic commands ###
