###
POST http://localhost:8080/api/v1/user/register
Content-Type: application/json

{
    "username":"test_username1",
    "password":"test_passoword1",
    "email":"nsm4421@naver.com",
    "provider":"NONE"
}

###
POST http://localhost:8080/api/v1/user/login
Content-Type: application/json

{
    "username":"test_username2",
    "password":"test_passoword2",
    "provider":"NONE"
}