name: flutter_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  timeago: ^3.7.0
  cached_network_image: ^3.3.1
  flex_color_scheme: ^7.3.1
  flutter_cache_manager: ^3.3.1
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  go_router: ^14.2.7
  pausable_timer: ^3.1.0+3
  shimmer: ^3.0.0
  build_runner: ^2.4.11
  injectable: ^2.4.4
  get_it: ^7.7.0
  supabase_flutter: ^2.6.0
  flutter_dotenv: ^5.1.0
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.4
  path: ^1.9.0
  uuid: ^4.5.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  logger: ^2.4.0
  photo_manager: ^3.3.0
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_gen_runner: ^5.7.0
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/
    - .env
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500

# asset경로를 자동으로 생성
flutter_gen:
  assets:
    enabled: true
  output: lib/shared/style/generated
  line_length: 80
  integrations:
    flutter_svg: true
