spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/voucher?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1221
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size:20
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    show-sql: true         # 쿼리를 표준 출력으로
    properties:
      hibernate:
        format_sql: false  # 아름답게 출력

# Customizing
custom-config:
  batch:
    chunk-size: 5

