spring:
  profiles:
    active: dev # default
    group:
      local:
        - common
      prod:
        - common

---
spring:
  config:
    activate:
      on-profile: common
---
# development
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/compass
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
kakao:
  api:
    base-url: "https://dapi.kakao.com/v2/local/search/address.json"
    secret-key: ${KAKAO_API_SECRET_KEY}

---
# production
spring:
  config:
    activate:
      on-profile: prod